name: Push Tag


on:
  push:
    tags:
      - '*'
    # branches:
      # - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: change-on-tags
        with:
          base: HEAD
          filters: |
            src:
              - 'changed'

      - name: Debug
        if: steps.change-on-tags.outputs.src == 'true'
        run: |
          echo "Files changed on tag push"

      - name: debug value
        run: |
          echo "github:"
          echo "${{ toJson(github) }}"
