name: "\"if\" debug"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  debug-job:
    name: debug job
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: debug
        run: |
          echo debug
          echo ------------------------------------------
          echo - github.event_name ${{ github.event_name }}
          echo - github.event.action ${{ github.event.action }}
          echo - github.event.pull_request.merged ${{ github.event.pull_request.merged }}
          echo - github ${{ github }}
          echo - env ${{ env }}
          echo - job ${{ job }}
          echo - steps ${{ steps }}
          echo - needs ${{ needs }}
