name: "\"if\" debug"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  debug-job:
    name: debug job
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: debug
        if: ${{ github.ref == 'refs/heads/main' && event_name == 'push' }}
        run: |
          echo debug
          echo ------------------------------------------
          echo - github.event_name ${{ github.event_name }}
          echo - github.event.action ${{ github.event.action }}
          echo - github.event.pull_request.merged ${{ github.event.pull_request.merged }}
          echo - github 
          cat <<EOF
          ${{ toJSON(github) }}
          EOF
          echo - env
          cat <<EOF
          ${{ toJSON(env) }}
          EOF
          echo - job
          cat <<EOF
          ${{ toJSON(job) }}
          EOF
          echo - steps
          cat <<EOF
          ${{ toJSON(steps) }}
          EOF
          echo - "needs"
          cat <<EOF
          ${{ toJSON(needs) }}
          EOF
