name: "\"if\" debug"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  debug-job:
    name: debug job
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == 'true' }}

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: debug
        run: echo debug
