name: "\"if\" debug"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  debug-job:
    name: debug job
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: debug
        run: |
          echo debug
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
          echo ${{ github.event.pull_request.merged }}
